"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from neon_api import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class APIKeyCreateRequest:
    key_name: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('key_name') }})
    r"""A user-specified API key name. This value is required when creating an API key."""
    

