"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class BranchState(str, Enum):
    r"""The branch state"""
    INIT = 'init'
    READY = 'ready'
