"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import branch as shared_branch
from dataclasses_json import Undefined, dataclass_json
from neon_api import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class BranchesResponse:
    r"""Returned a list of branches for the specified project"""
    
    branches: list[shared_branch.Branch] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('branches') }})
    