"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EndpointPoolerMode(str, Enum):
    r"""The connection pooler mode. Neon supports PgBouncer in `transaction` mode only."""
    TRANSACTION = 'transaction'
