"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class EndpointType(str, Enum):
    r"""The compute endpoint type. Either `read_write` or `read_only`.
    The `read_only` compute endpoint type is not yet supported.
    """
    READ_ONLY = 'read_only'
    READ_WRITE = 'read_write'
