"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class OperationStatus(str, Enum):
    r"""The status of the operation"""
    RUNNING = 'running'
    FINISHED = 'finished'
    FAILED = 'failed'
    SCHEDULING = 'scheduling'
