"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from neon_api import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class ProjectQuota:
    r"""Per-project consumption quota. If quota is exceeded, then all active computes
    will be automatically suspended and it won't be possible to start them neither
    with API method call or with incoming proxy connections. The only exception is
    `logical_size_bytes`, which is applied on per-branch basis, i.e. only compute
    on the branch with `logical_size` exceeding quota will be suspended.
    
    Quotas are enforced based on per-project consumption metrics with the same names,
    which are reset at the end of each billing period (first day of the month).
    Logical size is also an exception here, as it represents the total size of data
    stored in some branch, so it's not reset.
    
    Zero quota value or empty mean 'unlimited'.
    """
    
    active_time_seconds: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('active_time_seconds'), 'exclude': lambda f: f is None }})
    r"""The total amount of wall-clock time allowed to be spent by project's compute endpoints."""
    compute_time_seconds: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('compute_time_seconds'), 'exclude': lambda f: f is None }})
    r"""The total amount of CPU seconds allowed to be spent by project's compute endpoints."""
    data_transfer_bytes: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('data_transfer_bytes'), 'exclude': lambda f: f is None }})
    r"""Total amount of data transferred from all project's branches using proxy."""
    logical_size_bytes: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('logical_size_bytes'), 'exclude': lambda f: f is None }})
    r"""Limit on the logical size of every project's branch."""
    written_data_bytes: Optional[int] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('written_data_bytes'), 'exclude': lambda f: f is None }})
    r"""Total amount of data written to all project's branches."""
    