"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import billingsubscriptiontype as shared_billingsubscriptiontype
from dataclasses_json import Undefined, dataclass_json
from neon_api import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ProjectOwnerData:
    branches_limit: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('branches_limit') }})
    email: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('email') }})
    subscription_type: shared_billingsubscriptiontype.BillingSubscriptionType = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('subscription_type') }})
    r"""Type of subscription to Neon Cloud.
    Notice that for users without billing account this will be \"UNKNOWN\" 
    """
    

