"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class Provisioner(str, Enum):
    r"""The Neon compute provisioner."""
    K8S_POD = 'k8s-pod'
    K8S_NEONVM = 'k8s-neonvm'
