"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import branch as shared_branch
from ..shared import connectiondetails as shared_connectiondetails
from ..shared import database as shared_database
from ..shared import endpoint as shared_endpoint
from ..shared import generalerror as shared_generalerror
from ..shared import operation as shared_operation
from ..shared import project as shared_project
from ..shared import role as shared_role
from dataclasses_json import Undefined, dataclass_json
from neon_api import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class CreateProject201ApplicationJSON:
    r"""Created a project.
    The project includes a connection URI with a database, password, and role.
    At least one non-protected role is created with a password.
    Wait until the operations are finished before attempting to connect to a project database.
    """
    
    branch: shared_branch.Branch = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('branch') }})
    connection_uris: list[shared_connectiondetails.ConnectionDetails] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('connection_uris') }})
    databases: list[shared_database.Database] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('databases') }})
    endpoints: list[shared_endpoint.Endpoint] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('endpoints') }})
    operations: list[shared_operation.Operation] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('operations') }})
    project: shared_project.Project = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('project') }})
    roles: list[shared_role.Role] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('roles') }})
    

@dataclasses.dataclass
class CreateProjectResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    create_project_201_application_json_object: Optional[CreateProject201ApplicationJSON] = dataclasses.field(default=None)
    r"""Created a project.
    The project includes a connection URI with a database, password, and role.
    At least one non-protected role is created with a password.
    Wait until the operations are finished before attempting to connect to a project database.
    """
    general_error: Optional[shared_generalerror.GeneralError] = dataclasses.field(default=None)
    r"""General Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    