"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import apikeycreateresponse as shared_apikeycreateresponse
from ..shared import generalerror as shared_generalerror
from typing import Optional


@dataclasses.dataclass
class CreateAPIKeyResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    api_key_create_response: Optional[shared_apikeycreateresponse.APIKeyCreateResponse] = dataclasses.field(default=None)
    r"""Created an API key"""
    general_error: Optional[shared_generalerror.GeneralError] = dataclasses.field(default=None)
    r"""General Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    