"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import generalerror as shared_generalerror
from ..shared import projectresponse as shared_projectresponse
from typing import Optional


@dataclasses.dataclass
class DeleteProjectRequest:
    
    project_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project_id', 'style': 'simple', 'explode': False }})
    r"""The Neon project ID"""
    

@dataclasses.dataclass
class DeleteProjectResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    general_error: Optional[shared_generalerror.GeneralError] = dataclasses.field(default=None)
    r"""General Error"""
    project_response: Optional[shared_projectresponse.ProjectResponse] = dataclasses.field(default=None)
    r"""Deleted the specified project"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    