"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import generalerror as shared_generalerror
from ..shared import roleresponse as shared_roleresponse
from typing import Optional



@dataclasses.dataclass
class GetProjectBranchRoleRequest:
    branch_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'branch_id', 'style': 'simple', 'explode': False }})
    r"""The branch ID"""
    project_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project_id', 'style': 'simple', 'explode': False }})
    r"""The Neon project ID"""
    role_name: str = dataclasses.field(metadata={'path_param': { 'field_name': 'role_name', 'style': 'simple', 'explode': False }})
    r"""The role name"""
    




@dataclasses.dataclass
class GetProjectBranchRoleResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    general_error: Optional[shared_generalerror.GeneralError] = dataclasses.field(default=None)
    r"""General Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    role_response: Optional[shared_roleresponse.RoleResponse] = dataclasses.field(default=None)
    r"""Successfully returned details for the specified role"""
    

