"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import generalerror as shared_generalerror
from ..shared import projectoperations as shared_projectoperations
from ..shared import projectupdaterequest as shared_projectupdaterequest
from typing import Optional



@dataclasses.dataclass
class UpdateProjectRequest:
    project_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project_id', 'style': 'simple', 'explode': False }})
    r"""The Neon project ID"""
    project_update_request: shared_projectupdaterequest.ProjectUpdateRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    




@dataclasses.dataclass
class UpdateProjectResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    general_error: Optional[shared_generalerror.GeneralError] = dataclasses.field(default=None)
    r"""General Error"""
    project_operations: Optional[shared_projectoperations.ProjectOperations] = dataclasses.field(default=None)
    r"""Updated the specified project"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

