"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import branchoperations as shared_branchoperations
from ..shared import branchupdaterequest as shared_branchupdaterequest
from ..shared import generalerror as shared_generalerror
from typing import Optional


@dataclasses.dataclass
class UpdateProjectBranchRequest:
    
    branch_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'branch_id', 'style': 'simple', 'explode': False }})
    r"""The branch ID"""
    branch_update_request: shared_branchupdaterequest.BranchUpdateRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    project_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'project_id', 'style': 'simple', 'explode': False }})
    r"""The Neon project ID"""
    

@dataclasses.dataclass
class UpdateProjectBranchResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    branch_operations: Optional[shared_branchoperations.BranchOperations] = dataclasses.field(default=None)
    r"""Updated the specified branch"""
    general_error: Optional[shared_generalerror.GeneralError] = dataclasses.field(default=None)
    r"""General Error"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    